# >>> Basic Setup | 基础设置 <<<

# Header | 主菜单
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  Home: http://waterstrong.me
  Archives: /archives
  Tag Cloud: /tags
  About: /about

# Link to your avatar | 填写头像地址
avatar: /img/head.jpg

# Small icon of Your site | 站点小图标地址
favicon: /img/favicon.png

# Social info. Bar | 社交信息展示
## Keep "mailto:" in Email | 设置 Email 时保留 "mailto:"
## Encrypt email 加密邮件地址 http://ctrlq.org/encode/
## RSS requires a plugin to take effect | 使用 RSS 需先安装对应插件 hexo-generator-feed
## Sitemap 安装对应插件 hexo-generator-sitemap
## https://github.com/hexojs/hexo-generator-feed
subnav:
  Email: "mailto:sqlin@thoughtworks.com"
  Github: "http://github.com/waterstrong"
  Wechat: "img/qrcode.png"
#  QQ: "#"
  Weibo: "http://weibo.com/waterstrong"
#  Twitter: "https://twitter.com/shuiqianglin"
  Facebook: "https://www.facebook.com/linshuiqiang"
  StackOverflow: "http://stackoverflow.com/users/6448085/waterstrong"
  #  Zhihu: "zhihu"
  #  Douban: "#"
  LinkedIn: "https://cn.linkedin.com/in/shuiqiang-lin-191a0a112"
  RSS: /atom.xml
  # Google: "#"
  # PayPal: "#"
  # Instagram: "#"
  # Flickr: "#"


# >>> Conments 评论系统 <<<
# Chose ONE as your comment system and keep others disable.
# 选一个作为网站评论系统，其他保持禁用。

disqus: 
  on: false
  shortname: waterstrongblog
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if you have set "disqus_shortname" in your site's "_config.yml"

duoshuo: 
  on: true
  domain: waterstrong
  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名前半部分
  # http://<要填的部分>.duoshuo.com (domain只填上<>里的内容，不要填整个网址)

youyan:
  #on: true
  id: 
  # 是否开启友言评论，http://www.uyan.cc/index.php
  # id 中填写你的友言用户数字ID，注册后进入后台管理即可查看
  # 友言服务在 Web 环境下运行，普通本地环境无法查看，请部署后在线上测试。


# >>> Style Customisation 样式自定义 <<<

# Background | 背景
## "background_sum": show images form /source/background/的图片数目
## "on: true": 自动随机显示这5张图片
## "on: false": 自定义显示图片设置background_image: 5
background:
  on: false
  background_sum: 7
  background_image: 0 # if "on: false", the background img is the one

# Set inline_code to style highlight text, 通过 inline_code 切换内置文本高亮样式
# Chose a highlight theme for code block, 通过 code_block 切换内置代码高亮配色主题
highlight_style:
  #on: true
  inline_code: 1  # Value: 0 - 9 可选
  code_block: 1  # Value: 0 - 4

# 自定义文章「引用部分」的样式
blockquote_style:
  on: false
  blockquote: 0  # Value: 0 - 7 可选, 0 is default style

# 左边栏宽度 px
left_col_width: 291

# 在阅读模式下默认显示左边栏
init_show_col: false

# 初始状态时是否显示目录
init_show_toc: true

# 目录中标题不换行
# Keep TOC title on the same line | 
toc_nowrap: false

# 自定义"阅读全文"链接按钮的显示文字
# Customize the text on excerpt link
excerpt_link: more #修改more>>的文字

# 是否显示边栏中的搜索框（仅样式，未添加搜索功能）
# Search Box in left column
search_box: true
# Your swiftype install key
swiftype_install_key: kWrco8T5WiVvGAF--sSf

# 是否开启主页及加载头像时的动画效果
# Animation in Homepage and Loading avatar
animate: true

# Load jQuery UI to style tooltips
# 工具提示框样式美化
jquery_ui: true

# >>> Small features | 小功能设置 <<<

# 是否开启边栏多标签切换
# Birdhouse button in left column
tagcloud: true

# Blogroll, Link exchange | 友情链接
# friends: false
friends:
  Koly: http://koly.me/
  who: #


#是否开启“关于我”。
aboutme: I'm Waterstrong! The man who has made up his mind to win will never say "Impossible"!
#aboutme: false

# 是否在新窗口打开链接
# Open ALL link in a new tab
open_in_new: false

# Customize feed link 自定义订阅地址
rss: /atom.xml


# >>> Vendors | 第三方工具 & 服务 <<<

# images viewer | 图片浏览器
## http://www.fancyapps.com/fancybox/
fancybox: true

# Display Math(LaTeX, MathML...) | 数学公式支持
## https://www.mathjax.org/
mathjax: false

# Socail Share | 是否开启分享
baidushare: true
# share: true  # Deprecated
# showshare: true

# 百度、谷歌站长验证。填写 HTML 标签 content
# Site Verification for Google and Baidu. HTML label content.
#google_site: 3uYD_HHAdzktaAWksT5naJ9iaR3GD25DNI77eRoqYlI
baidu_site: 9122feae2de1ae23df6a837a7c898ef1

# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X
#google_analytics: UA-75679138-1
baidu_analytics: 0eebfc18021c9d6853ca20f45d03d4a1 # enter Baidu Analytics hash key

# 不蒜子网站计数设置
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit: 本站到访数
  page_visit: 本页阅读量

# A标签提示
tip_title: true

# Loading
# Loading: true